### ISSUE TITLE
MDI icon not showing of showing incorrect

### ISSUE THREAD

**Issue by Zhaobab** [estevez-dev/ha_client#281]
Hi !

I try this new APP since 2 days, It's really awesome keep going guys !
I try to use custom icon for entity card (Lovelace UI) but app still use default:

```
entity: switch.plug_158d0001700170
hold_action:
  action: more-info
name: Veilleuse
tap_action:
  action: toggle
theme: Backend-selected
type: entity-button
icon: 'mdi:lightbulb'
```

Same for mdi:robot-vacuum ( who doesn't show at all).

WebUI :
![wechatimg108](https://user-images.githubusercontent.com/6453724/51822658-f6012180-2317-11e9-9a20-07ac83fd3299.jpeg)

App :
![wechatimg107](https://user-images.githubusercontent.com/6453724/51822668-fdc0c600-2317-11e9-8873-c5a4c3f8403e.png)
