### ISSUE TITLE
Null card is not supported yet 0.6.3

### ISSUE THREAD

**Issue by Klagio** [estevez-dev/ha_client#431]
1![](https://i.imgur.com/Ff110E8.png)

**Comment by estevez-dev** [comment]
It would be very helpful to get a config for one of those cards.

**Comment by Klagio** [comment]
Sorry, I was on phone, and could not finish to post
```

      - id: bc6d27ee25624352b5ee320ccef05219c1  # Automatically created id
        type: entity-filter
        card:
          title: Motion sensor ON
          show_header_toggle: false
        entities:
          - binary_sensor.pir_bathroom
          - binary_sensor.pir_corridor
          - binary_sensor.pir_foyer
          - binary_sensor.pir_entrance2

```
