### ISSUE TITLE
Conditional card not working properly

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#446]
I have set up conditional card and it is not working properly.

This is my config:
```
- type: conditional
  conditions:
    - entity: input_boolean.boysbedroomsensorstate
      state: "off"
    - entity: input_boolean.livingroomsensorstate
      state: "off"
    - entity: input_boolean.katysroomsensorstate
      state: "off"
    - entity: input_boolean.parentsroomsensorstate
      state: "off"
    - entity: input_boolean.kitchenroomsensorstate
      state: "off"
    - entity: input_boolean.bathroomsensorstate
      state: "off"
    - entity: input_boolean.darzslivingroom1sensorstate
      state: "off"
    - entity: input_boolean.darzsparentsroomsensorstate
      state: "off"
  card:
    type: markdown
    content: >
      ### Everything is off! 😃
```

Despite some of entities being on, markdown card is still shown.
