### ISSUE TITLE
Thermostat card is not rendered

### ISSUE THREAD

**Issue by andr2000** [estevez-dev/ha_client#498]
**HA Client version:** 0.7.2

**Home Assistant version:** 0.100.2

**Device name:** Nexus 5x

**Android version:** 8.1

**Connection type:** OpenVPN

**Login type:** "HA Login"

**Description**
Thermostat card is only partially rendered, please see screen shots
**Screenshots**
![Screenshot_20191108-145556](https://user-images.githubusercontent.com/827874/68478842-90907880-0239-11ea-961d-78efd2744dd8.png)
![Screenshot_20191108-145444](https://user-images.githubusercontent.com/827874/68478850-938b6900-0239-11ea-972b-78686893cc33.png)

**Logs**
1108 15:04:48 [Error] :  type 'bool' is not a subtype of type 'String' in type cast
```
Bunch of:
1108 15:04:48 [Error] :  type 'bool' is not a subtype of type 'String' in type cast
```

**Comment by estevez-dev** [comment]
Could you please show me the same controls but from web? Click three-dots on your thermostat card in web ui. Thanks.
Also what is the platform of this thermostat?

**Comment by andr2000** [comment]
```
- platform: mqtt
  name: "Thermostat Mode"
  qos: 1
  # Availability: gate on signal available.
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  # Current
  current_temperature_topic: "ebusd/b7v/z1RoomTemp"
  current_temperature_template: >
    {{ '%0.1f' | format(value | float) }}
  # Current action/status: expects idle, cooling, heating, drying, or off.
  action_topic: "ebusd/b7v/Hc1Status"
  action_template: >
    {% set values = { '0':'idle', '1':'heating' } %}
    {{ values[value] if value in values.keys() else 'idle' }}
  # Mode control: expects auto, off, cool, heat, dry, fan_only
  # but VRC has 0=off;1=modulating;2=thermostat
  # Map off->off, auto->modulating, heat->thermostat
  mode_state_topic: "ebusd/b7v/Hc1RoomTempSwitchOn"
  mode_state_template: >
    {% set values = { 'off':'off', 'modulating':'auto', 'thermostat':'heat' } %}
    {{ values[value] if value in values.keys() else 'idle' }}
  # FIXME: mode_command_topic has no value template, so climate control
  # will send mode as a string "modes[i]" to the MQTT topic, which
  # results in "auto" instead of "modulating" and "heat" instead of termostat
  # Work this around as described https://community.home-assistant.io/t/enhanced-version-of-mqtt-hvac-climate-platform-with-proper-history-chart/75304/31
  mode_command_topic: "quirk_ebusd_b7v_Hc1RoomTempSwitchOn_set"
  # FIXME: off requires quotes for some reason to be displayed in the card
  modes:
    - 'off'
    - auto
    - heat
  temperature_command_topic: "ebusd/b7v/z1ActualRoomTempDesired/set"
  temperature_state_topic: "ebusd/b7v/z1ActualRoomTempDesired"
  temp_step: 0.5
  initial: 18
  min_temp: 12
  max_temp: 24
```
