### ISSUE TITLE
entity-filter card seems to not honor per-entity state_filter override

### ISSUE THREAD

**Issue by dvv** [estevez-dev/ha_client#512]
**HA Client version:** [Main menu -> About HA Client]
0.7.5

**Home Assistant version:**
0.100.2

**Device name:**
Redmi 5 Plus

**Android version:**
8.1.0

**Description**
Given the both mentioned entities are "on" the following config shows them both in HA client (incorrect) while showing none on HA site (correct).
```
      - type: entity-filter
        title: Attention!
        show_empty: false
        state_filter:
          - "on"
        entities:
          - entity: binary_sensor.hru_network
            state_filter:
              - "off"
          - entity: binary_sensor.fru_network
            state_filter:
              - "off"
```
Please consider fixing. TIA
