### ISSUE TITLE
Camera not showing in picture-elements card

### ISSUE THREAD

**Issue by hellcry37** [estevez-dev/ha_client#564]
**Card name:**
Standard Home Assistant - type: picture-elements
**Link to card repository or web page:**
https://www.home-assistant.io/lovelace/picture-elements/

I've had my camera working ok on your app in this card, but now just doesn't load anymore.

Thanks in advance.

**Comment by estevez-dev** [comment]
Picture elements is not supported yet: #215 
Now it should be displayed as type:button. Is is not displayed at all?

**Comment by hellcry37** [comment]
It is not displayed at all, my camera is gone, puff, magic :)

**Comment by hellcry37** [comment]
I can upload some pictures if you want like we did via mail the other bugs that I reported, but basically camera doesn't show anymore at all. Used to work ok before this unsupported card stuff :)

**Comment by estevez-dev** [comment]
Could you please show the configuration of the missed card? You can copy the code clicking "Show code editor" when editing the card.

**Comment by hellcry37** [comment]
Sure thing.
```yaml
camera_image: camera.livingroom_1
camera_view: live
elements:
  - icon: 'mdi:arrow-up'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 50px
      right: 25px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: up
    type: icon
  - icon: 'mdi:arrow-down'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 0px
      right: 25px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: down
    type: icon
  - icon: 'mdi:arrow-left'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 25px
      right: 50px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: left
    type: icon
  - icon: 'mdi:arrow-right'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 25px
      right: 0px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: right
    type: icon
  - icon: 'mdi:arrow-top-left'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 50px
      right: 50px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: top_left
    type: icon
  - icon: 'mdi:arrow-top-right'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 50px
      right: 0px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: top_right
    type: icon
  - icon: 'mdi:arrow-bottom-left'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 0px
      right: 50px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: bottom_left
    type: icon
  - icon: 'mdi:arrow-bottom-right'
    style:
      background: 'rgba(255, 255, 255, 0.5)'
      bottom: 0px
      right: 0px
    tap_action:
      action: call-service
      service: foscam.ptz
      service_data:
        entity_id: camera.livingroom_1
        movement: bottom_right
    type: icon
entity: camera.livingroom_1
show_state: false
type: picture-elements
```
